import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import nft from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio website</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Hi, I'm
            </h3>
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Aravind S
            </h2>
            {/* <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Blockchain Developer
            </h3> */}
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Scroll down to know something more about me...
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="http://www.linkedin.com/in/aravind-srinivasan-088367291"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="https://github.com/Aravinds2511"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillGithub />
              </a>
              <a
                href="mailto:aravindvasang@gmail.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillMail />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"></p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"></p> */}
          </div>
          <div className="gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <a
                href="https://nft-marketplace-61m7p6rcn-arvnds-projects.vercel.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image src={nft} width={100} height={100} />
              </a>
              <h3 className="text-lg font-medium pt-8 pb-2 py-4 text-teal-600">
                <a
                  href="https://github.com/Aravinds2511/NFT_Marketplace"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  NFT MARKETPLACE (code)
                </a>
              </h3>
              <p className="py-2">
                Created an simple nft marketplace to create, sell and buy
                nfts...
              </p>
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Solidity</p>
              <p className="text-gray-800 py-1">Next.js</p>
              <p className="text-gray-800 py-1">Hardhat</p>
              <p className="text-gray-800 py-1">Pinata</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <a
                href="https://github.com/Aravinds2511/proof_of_stack_blockchain_prototype"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image src={nft} width={100} height={100} />
              </a>
              <h3 className="text-lg font-medium pt-8 pb-2 py-4 text-teal-600">
                <a
                  href="https://github.com/Aravinds2511/proof_of_stack_blockchain_prototype"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  PROOF-OF-STAKE(Prototype) (code)
                </a>
              </h3>
              <p className="py-2">
                Created a simple blockchain that implements proof of stake.
              </p>
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1"> P2P connection established</p>
              <p className="text-gray-800 py-1">
                Implemeted Block validation, signature validation and POS
                consensus protocol
              </p>
              <p className="text-gray-800 py-1">
                Has Api endpoints for blockchain state, info, transaction pool
                and transactions
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <a
                href="https://web3-tracking-app.vercel.app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image src={nft} width={100} height={100} />
              </a>
              <h3 className="text-lg font-medium pt-8 pb-2 py-4 text-teal-600">
                <a
                  href="https://github.com/Aravinds2511/Web3_Tracking_App/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  WEB3-TRACKING-APP (code)
                </a>
              </h3>
              <p className="py-2">
                Created a tracking app using blockchain technology.
              </p>
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">Solidity</p>
              <p className="text-gray-800 py-1">Next.js</p>
              <p className="text-gray-800 py-1">Hardhat</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <a
                href="https://weather-app-eosin-nine.vercel.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image src={nft} width={100} height={100} />
              </a>
              <h3 className="text-lg font-medium pt-8 pb-2 py-4 text-teal-600">
                <a
                  href="https://github.com/Aravinds2511/Weather_app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  WEATHER APP (code)
                </a>
              </h3>
              <p className="py-2">
                Created a weather app that provides weather conditions,
                forecasts and suggestions.
              </p>
              {/* <h4 className="py-4 text-teal-600">Design Tools I Use</h4> */}
              <p className="text-gray-800 py-1">WEB 2</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Certifications</h3>
            <div className="flex gap-10">
              <div className="text-center shadow-lg p-1 rounded-xl my-4  dark:bg-white flex-1 max-w-xs">
                <h3 className="text-lg font-medium pt-2 pb-1 py-4 text-violet-600">
                  <a
                    href="https://github.com/Aravinds2511/Weather_app"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    BEC Vantage(2020)
                  </a>
                </h3>
              </div>
              <div className="text-center shadow-lg p-1 rounded-xl my-4  dark:bg-white flex-1 max-w-xs">
                <h3 className="text-lg font-medium pt-2 pb-1 py-4 text-violet-600">
                  <a
                    href="https://simpli-web.app.link/e/I0KKZkO3kEb"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Blockchain Certification Training
                  </a>
                </h3>
              </div>
              <div className="text-center shadow-lg p-1 rounded-xl my-4  dark:bg-white flex-1 max-w-xs">
                <h3 className="text-lg font-medium pt-2 pb-1 py-4 text-violet-600">
                  <a
                    href="https://dapp-world.com/course/certificate-verification/7990"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Ethereum DApp Development
                  </a>
                </h3>
              </div>
            </div>
            <div className="flex gap-10">
              <div className="text-center shadow-lg p-1 rounded-xl my-4  dark:bg-white flex-1 max-w-xs">
                <h3 className="text-lg font-medium pt-2 pb-1 py-4 text-violet-600">
                  <a
                    href="https://olympus.mygreatlearning.com/courses/13502/certificate"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Blockchain Basics
                  </a>
                </h3>
              </div>
              <div className="text-center shadow-lg p-1 rounded-xl my-4  dark:bg-white flex-1 max-w-xs">
                <h3 className="text-lg font-medium pt-2 pb-1 py-4 text-violet-600">
                  <a
                    href="https://www.datacamp.com/statement-of-accomplishment/course/ce1e3c69b5602ffdb4f1c0a412164e551b568965?raw=1"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Python
                  </a>
                </h3>
              </div>
              <div className="text-center shadow-lg p-1 rounded-xl my-4  dark:bg-white flex-1 max-w-xs">
                <h3 className="text-lg font-medium pt-2 pb-1 py-4 text-violet-600">
                  <a
                    href="https://www.datacamp.com/statement-of-accomplishment/course/5e559b833a8837abb849a289604b6c00814fc473?raw=1"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Intermediate SQL Queries
                  </a>
                </h3>
              </div>
            </div>
          </div>

          <div>
            <h3 className="text-3xl mt-10 py-1 dark:text-white">
              Technologies
            </h3>
            <ul>
              <li>
                <h2 className="text-2xl mt-5 py-1 dark:text-white">
                  Languages:
                </h2>
                <p className="text-1xl py-1 dark:text-white">Solidity</p>
                <p className="text-1xl py-1 dark:text-white">Javascript</p>
                <p className="text-1xl py-1 dark:text-white">Python</p>
                <p className="text-1xl py-1 dark:text-white">C</p>
                <p className="text-1xl py-1 dark:text-white">Sql</p>
              </li>
              <li>
                <h2 className="text-2xl mt-5 py-1 dark:text-white">
                  Frameworks:
                </h2>
                <p className="text-1xl py-1 dark:text-white">Node js</p>
                <p className="text-1xl py-1 dark:text-white">Web3 js</p>
                <p className="text-1xl py-1 dark:text-white">Ethers js</p>
                <p className="text-1xl py-1 dark:text-white">React js</p>
                <p className="text-1xl py-1 dark:text-white">Next js</p>
              </li>
              <li>
                <h2 className="text-2xl mt-5 py-1 dark:text-white">Tools:</h2>
                <p className="text-1xl py-1 dark:text-white">Foundry</p>
                <p className="text-1xl py-1 dark:text-white">Hardhat</p>
                <p className="text-1xl py-1 dark:text-white">Truffle</p>
                <p className="text-1xl py-1 dark:text-white">Remix</p>
              </li>
            </ul>
          </div>
          {/* xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx */}
          {/* <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          {/* </div> */}
        </section>
      </main>
    </div>
  );
}
